/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--bg) / <alpha-value>)',
        'background-secondary': 'rgb(var(--bg-secondary) / <alpha-value>)',
        foreground: 'rgb(var(--fg) / <alpha-value>)',
        'foreground-secondary': 'rgb(var(--fg-secondary) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        'muted-light': 'rgb(var(--muted-light) / <alpha-value>)',
        card: 'rgb(var(--card) / <alpha-value>)',
        'card-hover': 'rgb(var(--card-hover) / <alpha-value>)',
        'card-foreground': 'rgb(var(--card-foreground) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-light': 'rgb(var(--border-light) / <alpha-value>)',
        input: 'rgb(var(--input) / <alpha-value>)',
        'input-border': 'rgb(var(--input-border) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--accent-hover) / <alpha-value>)',
        'accent-light': 'rgb(var(--accent-light) / <alpha-value>)',
        ring: 'rgb(var(--ring) / <alpha-value>)',
        highlight: 'rgb(var(--highlight) / <alpha-value>)',
        'highlight-hover': 'rgb(var(--highlight-hover) / <alpha-value>)',
        'highlight-light': 'rgb(var(--highlight-light) / <alpha-value>)',
      },
      boxShadow: {
        'theme-sm': 'var(--shadow-sm)',
        'theme-md': 'var(--shadow-md)',
        'theme-lg': 'var(--shadow-lg)',
        'theme-xl': 'var(--shadow-xl)',
        'theme-float': 'var(--shadow-float)',
        'theme-button': 'var(--shadow-button)',
      },
      borderRadius: {
        'theme': 'var(--radius)',
      },
      zIndex: {
        'base': '0',
        'content': '10',
        'sticky': '50',
        'overlay': '100',
        'modal': '200',
        'toast': '300',
      },
    },
  },
  plugins: [],
};
