name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.droplet_ip }} 
          username: root
          key: ${{ secrets.ssh_private_key }}
          script: |
            /var/www/Puurga/server-deploy.sh
